name: Template Sync
on:
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2 # important!
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: euphoricsystems/action-sync-template-repository@v2.5.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true
